#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx validate-branch-name
npx lint-staged

yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

yarn prettier ||
(
    echo 'SabaTamin Front End Team. 🤢🤮🤢🤮 - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn prettier:fix, add changes and try commit again.';
    false;
)

#yarn test

yarn lint ||
(
    echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
            ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

